### ISSUE TITLE
Need to new collaborators, maintainer

### ISSUE THREAD

**Issue by e-jigsaw** [e-jigsaw/gulp-riot#117]
No longer I do not use Riot.js and gulp in production. I want to rewrite this plugin by ES6, but I have no match time. Then let me know if you are interested in being a collaborators. Please reply.

Thanks

**Comment by ghost** [comment]
If you'd still like, I can collaborate on this repository and handle the rewrite in ES6 syntax.

**Comment by e-jigsaw** [comment]
@TheDancingCode Thank you for offer. I always waiting PR.

**Comment by e-jigsaw** [comment]
Done!
