### ISSUE TITLE
output doesn't match cli version when run with type : 'none'

### ISSUE THREAD

**Issue by jesseditson** [e-jigsaw/gulp-riot#20]
Running with type : 'none', doesn't properly parse methods the same way as the npm `riot` package.

For instance, when a tag body contains:

``` javascript
somefunction() {
  // body
}
```

The command line outputs:

``` javascript
this.somefunction() {
  // body
}.bind(this);
```

whereas when run as a gulp task, the output is instead unchanged. Because this won't parse in a browser, it will break any tag with a function defined in it.

**Comment by e-jigsaw** [comment]
I checked with https://github.com/e-jigsaw/gulp-riot/blob/master/test/index.coffee#L80-L107

Can I see your `gulpfile` and `.tag` file? I think something wrong these files.
