### ISSUE TITLE
none of the option works

### ISSUE THREAD

**Issue by duongphuhiep** [e-jigsaw/gulp-riot#46]
none of the option works, am I missing something?

```
var gulp = require('gulp');
var gp_riot = require('gulp-riot');

 gulp.task('compile:tag', function(){
     return gulp.src(['app/**/*.tag'])
         .pipe(gp_riot({modular: true}))
         .pipe(gulp.dest('gen'));
 });
```

Here I expected to make each .tag a module, but it still generate the plain one line javascript

```
riot.tag('language-selector'....
```

I'm using riot 2.2.4

**Comment by e-jigsaw** [comment]
@duongphuhiep Thanks your report. I will check it out.

**Comment by e-jigsaw** [comment]
@duongphuhiep I checked your gulpfile. And code is generate with tagger codes. Could you show all of `.tag` code? Thanks

**Comment by duongphuhiep** [comment]
The option is not working so I don't use option in my project so far:
https://github.com/duongphuhiep/hcqh/tree/master/app
You can create a project

**Comment by duongphuhiep** [comment]
The option is not working so I don't use option in my project so far:
https://github.com/duongphuhiep/hcqh/tree/master/app
You can create a simple  project to reproduce the problem (i can do it later to show you)  

It seem that some compiler options are now handled by the riot client tools,  not by the riot compiler that gulp-riot is using

(I read the code of 2.2.4, but I might mistaken)

**Comment by e-jigsaw** [comment]
@duongphuhiep Whoops, You are using `gulp-riot@0.2.18`. Modular options are added `v0.3.0`. You should upgrade `gulp-riot` version.

**Comment by duongphuhiep** [comment]
ok, thanks!
