### ISSUE TITLE
gulp-riot failing on require with 0.3.2

### ISSUE THREAD

**Issue by lucidtech** [e-jigsaw/gulp-riot#59]
I get `SyntaxError: Unexpected token ILLEGAL` with 0.3.2 when `riot = require('gulp-riot')` is evaluated in gulpfile.  require is complaining about riot's use of backticks in riot/lib/server/index.js.  I get the same when trying to use riot server side compilation in node directly (i.e. w/o gulp-riot)... so since gulp-riot is using the server side compilation of riot - I am not sure how to get gulp-riot 0.3.2 to run at all.

**Comment by e-jigsaw** [comment]
@lucidtech Have you tried to newer version 0.4.0?

**Comment by lucidtech** [comment]
hi. sorry... my node was < 4.0 which was the problem.
