### ISSUE TITLE
Detailed debug info?

### ISSUE THREAD

**Issue by ilearnio** [e-jigsaw/gulp-riot#61]
Hi. I'm using your plugin in my project for long time. It works OK, but it is often happens, when I making mistakes somewhere in my components or updating some plugins, it is usually gives me this kind of error in terminal:

```
{ [Error: Compiler Error: SyntaxError: unknown: Unexpected token (1:30)]
  message: 'Compiler Error: SyntaxError: unknown: Unexpected token (1:30)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-riot',
  __safety: { toString: [Function: bound ] } }
```

Maybe you can add some information about the file at which Riot's compiler throws an error? It would really save a lot of time.

Right now, I added a temporary `console.log` to the plugin, like so:

``` javascript
// gulp-riot/build/index.js:24
try {
  compiledCode = compile(file.contents.toString(), opts);
} catch (e$) {
  err = e$;
  console.log('Unable to compile component: ' + file.path); <<--- here
  return callback(new gutil.PluginError('gulp-riot', "Compiler Error: " + err));
}
```

**Comment by e-jigsaw** [comment]
@ilearnio v0.4.2 released! Thanks for suggestion

**Comment by ilearnio** [comment]
Awesome! Thanks! :+1:
