### ISSUE TITLE
Hi, I wanna know how to compile some directory's tags into one js

### ISSUE THREAD

**Issue by dongtong** [e-jigsaw/gulp-riot#69]
Hi, I wanna know how to compile some directory's tags into one js.

Thanks a lot

**Comment by afwilliams** [comment]
Hello, I am using [riotify](https://github.com/jhthorsen/riotify) for compile my `tags` in one `js`  file.

```
var gulp = require('gulp');
var browserify = require('browserify');
var riotify = require('riotify');
var source = require('vinyl-source-stream');

gulp.task('browserify', function () {
    return browserify({
        debug: true,
        entries: ['./scripts/main.js'],
        transform: [riotify]
    }).bundle()
        .pipe(source('main.bundle.js'))
        .pipe(gulp.dest('./dist/'));
});

gulp.task('default', ['browserify']);
```

this plugin use `browserify` for generate js file and you have the feature `require` for do call of components.

```
var riot = require('riot');
require('../tags/sample.tag');
riot.mount('sample');
```

I Like [riotify](https://github.com/jhthorsen/riotify)

**Comment by e-jigsaw** [comment]
@dongtong Hi

I use `gulp-concat` in my project.

```
gulp.task('riot', ()=> {
  gulp.src('directories')
      .pipe(riot())
      .pipe(concat('index.js'))
      .pipe(gulp.dest('dest'))
})
```

It is also good to use browserify as @afwilliams says.

Thanks

**Comment by dongtong** [comment]
@e-jigsaw  Yep, I used same solution as you pointed. BTW, Thanks a lot
