### ISSUE TITLE
Problem compiling custom tags

### ISSUE THREAD

**Issue by kokujin** [e-jigsaw/gulp-riot#75]
I have a problem with a custom tag as defined in the docs (html-elements-as-tags) http://riotjs.com/guide/#html-elements-as-tags

```
<ul riot-tag="my-tag"></ul>
```

Is there some configuration option that I am missing? Thanks.

**Comment by e-jigsaw** [comment]
@kokujin Hi, I need more details what your problem. Can you tell me your code or repo? Thanks

**Comment by kokujin** [comment]
Sorry for the issue @e-jigsaw, my bad. I made a mistake in my markup. It works now. Thanks.

**Comment by e-jigsaw** [comment]
:+1:
