### ISSUE TITLE
Problem compiling stylus in riot custom tag

### ISSUE THREAD

**Issue by lijujose-daffodil** [e-jigsaw/gulp-riot#80]
It works fine when using below code in my .tag file.
style
    :stylus
      .string-box
        color #000
        background-color #ef9a9a
        min-width 100px
        padding 3px

But I needed proper highlighting for .tag  in sublime Text3, So I replaced style with style(type="text/stylus").  and also removed :stylus, final code shown below:

style(type="text/stylus").  
    .string-box
      color #000
      background-color #ef9a9a
      min-width 100px
      padding 3px

when I compile above code it throw an error,  as shown below:
Error: 

> 1|     .string-box
>    2|       color #000
>    3|       background-color #ef9a9a
>    4|       min-width 100px

unexpected "space"

I am using below gulp code to compile .tag files:

gulp.task('jadeRiotComponents',['initialClean'], function() {
  return gulp.src('./src/components/*.tag')
      .pipe(riot({
        //type: 'coffeescript',
        template:'jade'
      }))
      .pipe(gulp.dest('./public/temp/'));
});

Please help me out.

**Comment by e-jigsaw** [comment]
I think your stylus syntax are invalid.

```
.string-box
  color #000
  background-color #ef9a9a
  min-width 100px
  padding 3px
```

Above code are collect.

**Comment by e-jigsaw** [comment]
Feel free to reopen this issue.
