### ISSUE TITLE
Issue with ES6 modules

### ISSUE THREAD

**Issue by perez-rich** [e-jigsaw/gulp-riot#83]
If I try to compile a Riot .tag file that also contains ES6 import statements Babel complains with the following SyntaxError: import' and 'export' may only appear at the top level. it looks like this is because you're wrapping the compiled riot code in a function, which includes the import statements. Do you know if there is a workaround for this?

Also below are the steps I took to reproduce this error.

If I have the following .tag file

```
import * as ajax from 'ajax'

<test>
    <div>
        Hello World
    </div>

    <script>
        ajax.call()
    </script>
</test>
```

And then run `gulp riot` which does this.

```
gulp.task('riot', function () {
    gulp.src('test.tag')
        .pipe(riot({
            type: 'babel',
            modular: true
        }))
        .pipe(babel({
            sourceRoot: 'public/js',
            plugins: [
                ['transform-es2015-modules-amd']
            ],
            presets: ['es2015-riot']
        }))
        .pipe(gulp.dest('test.js'))
})
```

I get the output below. This is coming from Babel complaining the import statement isn't at the top of the file. I saw docs talking about this but noticed it's example is using CommonJS module format while I'm using AMD. Is there a way to make my setup work or does Riot not support this yet?

```
SyntaxError: 'import' and 'export' may only appear at the top level (10:0)
   8 |   }
   9 | })(function(riot) {
> 10 | import * as ajax from 'ajax'
     | ^
  11 | 
  12 | riot.tag2('test', '<div> Hello World </div>', '', '', function(opts) {
  13 | define([], function () {
```

**Comment by e-jigsaw** [comment]
@imperez Type should be `es6` https://github.com/e-jigsaw/gulp-riot#available-option

``` js
        riot({
            type: 'es6',
            modular: true
        })
```

**Comment by perez-rich** [comment]
Ah actually the type wasn't the issue. The issue was modular option set to true. Once I got rid of that all was well since the the riot code wasn't being wrapped in the function.

**Comment by aMarCruz** [comment]
@imperez , @e-jigsaw , riot-compiler v2.5.4 have limited support to ES6 modules, please see the [Guide](https://github.com/riot/compiler/blob/master/doc/guide.md)
