### ISSUE TITLE
Example for using custom css parser with autoprefixer

### ISSUE THREAD

**Issue by bjork24** [e-jigsaw/gulp-riot#98]
Does anyone have a working example where compiled css is passed through autoprefixer via the `parsers.css` option?

**Comment by e-jigsaw** [comment]
I think `postcss.process` is async function so it is might be difficult.

**Comment by bjork24** [comment]
@e-jigsaw Do the `parsers` functions only work if they're sync?

**Comment by e-jigsaw** [comment]
@bjork24 I read http://riotjs.com/api/compiler/#css-parser . I do not inspect not mutch.

**Comment by lancetharper** [comment]
@bjork24 Yep, only sync. https://github.com/riot/compiler/issues/87
